name: CI

on: [push]

env:
  USER_NAME: "ThisIsAUserName"

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Find and Replace - Using Secrets
      run: find *.xml -type f -exec sed -i ''s/#{CString}#/${{ secrets.CString }}/g'' {} \;
    - name: Bash - Show XML Contents
      run: cat Example.xml
    - name: Find and Replace User Name - Using Build Variable
      run: find *.json -type f -exec sed -i ''s/#{UName}#/${{ env.USER_NAME }}/g'' {} \;
    - name: Find and Replace Password - Using Build Variable
      run: find *.json -type f -exec sed -i ''s/#{PWord}#/${{ secrets.PWord }}/g'' {} \;
    - name: Bash - Show JSON Contents
      run: cat Example.json
